### ISSUE TITLE
-discord-command Appears to do nothing.

### ISSUE THREAD

**Issue by HadetTheUndying** [Stieneee/mumble-discord-bridge#16]
I have tried using the default string and setting a string manually. Neither are working. Here is my config.

```
MUMBLE_ADDRESS=mumble.server
MUMBLE_USERNAME=Discord-Bridge
MUMBLE_CHANNEL=Lobby
MUMBLE_PASSWORD=
MUMBLE_INSECURE=1

DISCORD_TOKEN=mybottoken
DISCORD_GID=myguild
DISCORD_CID=mychannel
DISCORD_DISABLE_TEXT=true
DISCORD_COMMAND="bridge"
```

**Comment by stryan** [comment]
Just to double check, the command string should be prefaced an exclamation point i.e. "!bridge" not just "bridge. Are you doing that?

**Comment by HadetTheUndying** [comment]
Correct. I am in a voice channel saying "!bridge"

**Comment by stryan** [comment]
Are you running the bridge in "constant" mode? This is the default mode, and since it's designed to run all the time it doesn't accept manual commands. You can add "MODE=auto" or "MODE=manual" to your env file to switch it to auto or manual mode.

Otherwise, if you type "!bridge link" in a text channel while you're in a voice channel, do you see the following in the logs?
<code>Trying to join GID (GID number) and VID (VID number)</code>

**Comment by HadetTheUndying** [comment]
Changing the mode to Auto did work. Now When I tell it to link it autojoins the channel set in the ,env file. I assume that's intended though and I'll have to manually move the bridge to a different channel. I'll make a PR updating the README.md because the way the functionality is described doesn't make this very clear. All good. Thank you for the help.

**Comment by stryan** [comment]
I'm actually fixing that right now over in my fork so once I'm done testing for the night I'll PR something that makes it behave similar to what you expect.
