### ISSUE TITLE
Mumble stops receiving notifications

### ISSUE THREAD

**Issue by Stieneee** [Stieneee/mumble-discord-bridge#17]
Mumble stops receiving welcome messages and when users connect to discord. Nothing in the logs to suggest a starting point.

@stryan have you noticed this feature breaking after prolonged running?

**Comment by stryan** [comment]
Hmm, I haven't seen anything like that yet. Since that should all be triggered by event handlers, possibly something wrong in discordgo? How prolonged are we talking? I don't think I've run the bridge for more then a few days straight recently due to various reasons.

Now that there's a debug config option it's on my list to add better debug logs so maybe that will help.

**Comment by Stieneee** [comment]
Created issue layeh/gumble#55 as it appears to be Gumble or Mumble issue.

[Gumble-Echo-Test](https://github.com/Stieneee/gumble-echo-test) can be used to reproduce the issue.

**Comment by stryan** [comment]
Gotcha, following along on the Gumble issue as well. If it's occurring after ~24 hours of connection it would make sense while I haven't run into it since I run only in auto mode.
