### ISSUE TITLE
issues with !DISCORD_COMMAND unlink

### ISSUE THREAD

**Issue by rhetr** [Stieneee/mumble-discord-bridge#35]
i'm having issues with using `!DISCORD_COMMAND unlink`:

- if the bridge is in auto mode, when I call the `unlink` command it disconnects and then immediately reconnects
- if I first call the `auto` command to disable auto mode, subsequently calling `unlink` does nothing

**Comment by stryan** [comment]
For part 1, that is actually expected behaviour if there's still people on both the mumble end and the discord end. If you want to kill the bridge while people are on both sides you should do as you did in part 2 and toggle it to manual mode first.

For part 2, yeah I see the issue. Looks like when the bridge is toggled to manual it clears the Discord voice channel ID the bot is paying attention to. I think I wrote that code and I don't remember why I did, so I'm removing the line. Shouldn't be a problem anyway; I believe that value is only referenced when the link and unlink commands are parsed and when "link" is processed it pulls the channel ID from the sender.
