### ISSUE TITLE
Pulling in new features: Big PR vs etc

### ISSUE THREAD

**Issue by stryan** [Stieneee/mumble-discord-bridge#6]
I've been using and working on my own fork of this project for a couple weeks now and it's gotten to the point where I'd like to upstream at least some of my additions. The full fork is over [here](https://github.com/stryan/mumble-discord-bridge) but in brief summary I've added the following features:
- Three separate runtime modes: constant (as it is now), manual, and automatic startup
- Discord bot shows number of users in mumble as status
- Control the bridge through Discord
- Announcements in Mumble when user joins Discord
- Auto-join specific Mumble channel

Unfortunately, I didn't expect expect to do this much so the resulting PR is pretty big (~600 added, ~100 removed) so I wasn't comfortable creating it with no warning. Instead, I'm here asking how you would prefer me to submit these changes. Something like one of the following:

1. Submit the PR as is and promise to do smaller ones next time
2. Break it up as best I can into a 1 or 2 smaller PR's
3. Re-fork and re-do the changes to make multiple small PRs
4. Cherry pick a few smaller features (i.e. Discord bot status) and PR those.
5. No PR necessary, I'll add the features myself if wanted

I'm fine with whatever; I recognize my changes ended up restructuring things quite a bit and if you would prefer to take things one at a time or not use my code that's absolutely fine.

**Comment by Stieneee** [comment]
Hey, Yes, it would be great to bring in your work! 

I actually looked at some of your work on the weekend and tried tinkering with the connect disconnect notices on the weekend. I just cleaned it up tonight and pushed it to this branch [msg-events](https://github.com/Stieneee/mumble-discord-bridge/tree/msg-events). It was inspired by some of your work but handles tracking discord users a little more efficiently. It turns out discord has an internal state of the users, which is updated from voiceUpdate messages. My implementation periodically checks that internal state for changes and stores the currently know users in a local map. The speed-up comes from not having to call S.User(id) to look up the user name. This is an actual HTTP call and is slow when looping through in serial. I haven't checked to see if usernames are cached in discordgo. Side note we can get a user count by just looking at the map's length (no need for +1 -1). I do that once somewhere in my new branch.

I like your runtime options. I was lazy handling mumble disconnects and opted to have the application recycle. It appears your work brings it closer to handling mumble connections better.

Your mumble count as discord status is cleaver. I also implemented direct messages to discord users while connected to the voice channel when users join or leave mumble.

At this point, it might be easier if I merge your work and then apply my tinkering to the discordUser map and count.

**Comment by stryan** [comment]
Interesting, I didn't realize that User lookups were HTTP calls; I'll have to work that into my fork.  But yeah, I do actually use the internal Users map when locking for VoiceState Disconnects and for handling the manual commands. Personally, I prefer to rely on the discordgo event handlers so I don't have to think about thread-safety as much, so I tried to handle it from that perspective. I plan on rewriting that section once discordgo 0.23 comes out with PreviousState as a part of the state update. The user count int is just legacy logic from when I was only counting the number of users instead of who was actually there. This was a good kick to the rear to remind me to clear that out :).

Fun story about the mumble count; originally I had written a discord bot to do just that, show the mumble count as a status. When I found your project my first thought was to combine my bot with it as a quick modification. Which then led to keeping track of member count of both sides and so on and so forth until a lot of "quick modifications" later we ended up here.

I would suggest Discord DMing (and the announcements to Mumble) should both probably be configured options.

When you say you'll merge it, do you mean option 5? Or as in merging one pull request?

**Comment by Stieneee** [comment]
I agree that the messages should be flagged, let's get things merged together before we add more functionality.

Let's do option 1 and get everything merged in.
